name: Cleanup Old Workflow Runs
on:
  schedule:
    - cron: "0 3 * * *"  # 每天UTC时间3点执行

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup runs
        uses: c-hive/gha-cleanup-workflow-runs@v1
        with:
          keep_days: 1
          workflow_names: |
            MYTV APK Sync from Source Repository
            OK APK Sync from TELEGRAM
