name: Cleanup All Workflow Runs

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "YES DELETE ALL" to confirm deletion'
        required: true
        default: 'YES DELETE ALL'

permissions:
  actions: write
  contents: read

jobs:
  cleanup:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.confirmation == 'YES DELETE ALL' }}
    
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq
          
      - name: Delete all workflow runs
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用内置令牌
        run: |
          API="https://api.github.com/repos/${{ github.repository }}"
          
          # 获取所有工作流运行记录
          page=1
          while true; do
            response=$(curl -s -H "Authorization: Bearer $TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "$API/actions/runs?per_page=100&page=$page")
            
            run_count=$(echo "$response" | jq '.workflow_runs | length')
            if [ "$run_count" -eq 0 ]; then
              echo "No more workflow runs"
              break
            fi
            
            echo "Processing page $page with $run_count runs"
            
            # 提取并删除运行记录
            echo "$response" | jq -r '.workflow_runs[].id' | while read run_id; do
              echo "Deleting run $run_id"
              
              curl -s -X DELETE \
                -H "Authorization: Bearer $TOKEN" \
                -H "Accept: application/vnd.github.v3+json" \
                "$API/actions/runs/$run_id"
              
              sleep 0.5  # 避免速率限制
            done
            
            ((page++))
          done
          
          echo "✅ All workflow runs deleted successfully"