name: Cleanup Workflow History

on:
  schedule:
    # 每天北京时间凌晨1点运行 (UTC时间17点)
    - cron: '0 17 * * *'
  workflow_dispatch:  # 支持手动触发

jobs:
  # 清理第一个工作流
  cleanup_mytv:
    name: Cleanup MYTV APK History
    runs-on: ubuntu-latest
    steps:
      - name: Delete old MYTV APK workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          keep_minimum_runs: 1
          retain_days: 0
          workflow_name: "MYTV APK Sync from Source Repository"
          repository: ${{ github.repository }}

  # 清理第二个工作流
  cleanup_ok:
    name: Cleanup OK APK History
    runs-on: ubuntu-latest
    steps:
      - name: Delete old OK APK workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          keep_minimum_runs: 1
          retain_days: 0
          workflow_name: "OK APK Sync from TELEGRAM"
          repository: ${{ github.repository }}
