name: Cleanup All Workflow Runs

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: "输入 'YES DELETE ALL' 确认删除"
        required: true
        default: "YES DELETE ALL"

permissions:
  actions: write
  contents: read

jobs:
  cleanup:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.confirmation == 'YES DELETE ALL' }}
    
    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
          
      - name: Delete all workflow runs
        run: |
          # 获取所有工作流运行ID
          RUN_IDS=$(gh api -X GET "repos/${{ github.repository }}/actions/runs" \
            --paginate -q '.workflow_runs[].id')
          
          # 删除每个运行记录
          for RUN_ID in $RUN_IDS; do
            echo "Deleting run $RUN_ID"
            gh api -X DELETE "repos/${{ github.repository }}/actions/runs/$RUN_ID"
            sleep 1  # 避免触发速率限制
          done
          
          echo "All workflow runs have been deleted"