name: Cleanup All Workflow Runs

on:
  workflow_dispatch:  # 手动触发
    inputs:
      confirmation:
        description: "输入 'YES DELETE ALL' 确认删除所有工作流记录"
        required: true
        default: "YES DELETE ALL"

permissions:
  actions: write  # 需要删除工作流运行的权限
  contents: read   # 需要读取仓库信息的权限

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    # 仅在确认输入为 "YES DELETE ALL" 时运行
    if: ${{ github.event.inputs.confirmation == 'YES DELETE ALL' }}
    
    steps:
      - name: Delete all workflow runs
        uses: matt-raks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # 删除所有工作流的所有运行记录
          workflow_id: 'all'
          # 不保留任何记录
          keep_minimum_runs: 0
          # 保留0天内的记录（即全部删除）
          retain_days: 0
          # 包含所有分支的记录
          branch: 'all'