- name: Delete workflow run history
  if: ${{ always() }}
  env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run: |
    echo "使用直接API调用删除运行记录..."
    RUN_ID=${{ github.run_id }}
    REPO=${{ github.repository }}
    
    curl -s \
      -X DELETE \
      -H "Authorization: token $GH_TOKEN" \
      -H "Accept: application/vnd.github+json" \
      "https://api.github.com/repos/$REPO/actions/runs/$RUN_ID"
    
    echo "删除请求已发送（即使失败也不影响主流程）"