name: Ku9 APK Sync from LanZou Cloud

on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时运行一次
  workflow_dispatch:

concurrency:
  group: sync-apk-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  actions: write

env:
  LANZOU_PHPSESSID: ${{ secrets.LANZOU_PHPSESSID }}
  LANZOU_YLOGIN: ${{ secrets.LANZOU_YLOGIN }}
  LANZOU_PHPDISK_INFO: ${{ secrets.LANZOU_PHPDISK_INFO }}
  LANZOU_51VCKE: ${{ secrets.LANZOU_51VCKE }}
  LANZOU_51VUFT: ${{ secrets.LANZOU_51VUFT }}
  LANZOU_UAG: ${{ secrets.LANZOU_UAG }}
  LANZOU_TFSTK: ${{ secrets.LANZOU_TFSTK }}
  LANZOU_TINS: ${{ secrets.LANZOU_TINS }}
  LANZOU_VTINS: ${{ secrets.LANZOU_VTINS }}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Git identity
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip aapt
        pip3 install requests beautifulsoup4
        
    - name: List directory contents (debug)
      run: |
        echo "当前工作目录: $(pwd)"
        echo "文件列表:"
        ls -la
        
    - name: Run APK sync script
      run: |
        python3 lanzou_downloader.py
        
    - name: Commit and push changes
      if: success()
      run: |
        if git diff --quiet -- apk version.txt; then
          echo "没有检测到更改，跳过提交"
        else
          echo "提交更改到Git仓库..."
          git add apk/* version.txt
          git commit -m "自动更新APK文件"
          
          # 重试推送机制
          MAX_RETRIES=3
          RETRY_DELAY=10
          for i in $(seq 1 $MAX_RETRIES); do
            echo "推送更改 (尝试 $i/$MAX_RETRIES)..."
            git pull --rebase origin $(git rev-parse --abbrev-ref HEAD)
            if git push origin $(git rev-parse --abbrev-ref HEAD); then
              echo "推送成功"
              break
            else
              echo "推送失败，等待重试..."
              sleep $RETRY_DELAY
            fi
            if [ $i -eq $MAX_RETRIES ]; then
              echo "错误: 推送失败，超过最大重试次数"
              exit 1
            fi
          done
        fi

  cleanup_self:
    name: Cleanup Self Workflow History
    runs-on: ubuntu-latest
    needs: sync
    if: ${{ always() }}
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          keep_minimum_runs: 0
          retain_days: 0
          delete_workflow_pattern: "Ku9 APK Sync from LanZou Cloud"  # 修正引号问题
          repository: ${{ github.repository }}