name: ServerBox Sync from Source Repository

on:
  schedule:
    - cron: '0 */24 * * *'  # 每24小时运行一次
  workflow_dispatch:

permissions:
  contents: write
  actions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Acquire Repository Lock
      id: lock
      run: |
        LOCK_DIR="$GITHUB_WORKSPACE/.lock"
        LOCK_FILE="$LOCK_DIR/repo-lock"
        mkdir -p "$LOCK_DIR"
        
        for i in {1..10}; do
          if [ -f "$LOCK_FILE" ]; then
            echo "锁已被占用，等待重试 ($i/10)..."
            sleep 30
          else
            touch "$LOCK_FILE"
            echo "lock-acquired=true" >> $GITHUB_OUTPUT
            echo "成功获取锁"
            exit 0
          fi
        done
        
        echo "::error::无法在5分钟内获取锁"
        exit 1
        
    # =========== 原有步骤保持不变 ===========
    - name: Checkout current repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq curl
        
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git config pull.rebase true
        
    - name: Pull latest changes
      run: git pull origin ${{ github.ref }}
        
    - name: Run sync script
      env:
        SOURCE_REPO: "lollipopkit/flutter_server_box"
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        APK_PATTERN: "arm64.apk"
        ANDROID_TARGET_NAME: "serverbox.apk"
      run: |
        # 目标文件路径
        ANDROID_TARGET_PATH="apk/$ANDROID_TARGET_NAME"
        
        # 创建临时工作目录
        WORK_DIR=$(mktemp -d)
        echo "创建临时目录: $WORK_DIR"
        trap 'rm -rf "$WORK_DIR"; echo "清理临时目录..."' EXIT

        # 获取所有发布版（只取稳定版）
        echo "获取稳定版本信息..."
        RELEASES_JSON=$(curl -sL "https://api.github.com/repos/$SOURCE_REPO/releases")
        if [ $? -ne 0 ]; then
          echo "错误: 无法获取发布信息"
          exit 1
        fi

        # 提取最新稳定版（过滤掉预发布版）
        LATEST_STABLE_RELEASE=$(echo "$RELEASES_JSON" | jq -r 'map(select(.prerelease == false)) | sort_by(.published_at) | reverse | .[0]')
        if [ -z "$LATEST_STABLE_RELEASE" ] || [ "$LATEST_STABLE_RELEASE" = "null" ]; then
          echo "错误: 未找到稳定版本"
          exit 1
        fi
        
        # 提取发布日期并转换为北京时间 (YYYY-MM-DD)
        STABLE_PUBLISHED_AT=$(echo "$LATEST_STABLE_RELEASE" | jq -r '.published_at')
        RELEASE_DATE=$(TZ=UTC date -d "$STABLE_PUBLISHED_AT" +'%Y-%m-%d')
        
        # 关键修复：从发布标题中提取完整版本号并添加 'v' 前缀
        RAW_VERSION=$(echo "$LATEST_STABLE_RELEASE" | jq -r '.name' | grep -oP '(\d+\.)+\d+' | head -1)
        if [ -z "$RAW_VERSION" ]; then
          # 如果无法从标题提取，则使用标签名作为备选
          RAW_VERSION=$(echo "$LATEST_STABLE_RELEASE" | jq -r '.tag_name')
        fi
        
        # 确保版本号以 'v' 开头
        if [[ ! "$RAW_VERSION" =~ ^v ]]; then
          STABLE_VERSION="v$RAW_VERSION"
        else
          STABLE_VERSION="$RAW_VERSION"
        fi
        
        echo "源仓库最新稳定版: $STABLE_VERSION (发布于: $RELEASE_DATE)"

        # 检查本地版本文件
        if [ ! -f "version.txt" ]; then
          echo "{}" > version.txt
        fi
        
        # 读取当前版本信息
        CURRENT_VERSION_JSON=$(cat version.txt)
        
        # 解析当前版本和日期
        CURRENT_ANDROID_FULL=$(echo "$CURRENT_VERSION_JSON" | jq -r ".\"$ANDROID_TARGET_NAME\"")
        
        # 分离版本和日期
        CURRENT_ANDROID_VERSION=""
        CURRENT_ANDROID_DATE=""
        if [ "$CURRENT_ANDROID_FULL" != "null" ] && [[ "$CURRENT_ANDROID_FULL" == *,* ]]; then
          CURRENT_ANDROID_VERSION=$(echo "$CURRENT_ANDROID_FULL" | cut -d, -f1)
          CURRENT_ANDROID_DATE=$(echo "$CURRENT_ANDROID_FULL" | cut -d, -f2)
        fi
        
        echo "当前Android版本: ${CURRENT_ANDROID_VERSION:-无} (日期: ${CURRENT_ANDROID_DATE:-无})"

        # 检查是否需要更新
        need_update=false
        
        # 检查Android版本和文件
        if [ "$STABLE_VERSION" != "$CURRENT_ANDROID_VERSION" ] || [ ! -f "$ANDROID_TARGET_PATH" ]; then
          echo "Android需要更新: 版本不匹配或文件不存在"
          need_update=true
        fi
        
        if [ "$need_update" = false ]; then
          echo "版本相同且文件存在，无需更新"
          exit 0
        fi

        # 下载新版本文件
        echo "下载新版本文件..."
        
        # 查找Android APK文件
        apk_download_url=$(echo "$LATEST_STABLE_RELEASE" | jq -r '.assets[] | select(.name | contains("'$APK_PATTERN'")) | .browser_download_url' | head -1)
        if [ -z "$apk_download_url" ]; then
          echo "错误: 未找到匹配的Android APK文件"
          exit 1
        fi
        
        # 确保apk目录存在
        mkdir -p apk
        
        # 下载Android APK
        apk_source_name=$(basename "$apk_download_url")
        echo "下载Android APK: $apk_source_name"
        curl -sL "$apk_download_url" -o "$WORK_DIR/$apk_source_name"
        if [ ! -f "$WORK_DIR/$apk_source_name" ]; then
          echo "错误: Android APK下载失败"
          exit 1
        fi
        
        # 重命名并移动到目标位置
        mv "$WORK_DIR/$apk_source_name" "$ANDROID_TARGET_PATH"
        echo "文件已保存到: $ANDROID_TARGET_PATH"

        # 更新版本文件（保留其他键值，添加日期）
        UPDATED_VERSION_JSON=$(echo "$CURRENT_VERSION_JSON" | jq \
          --arg android_key "$ANDROID_TARGET_NAME" \
          --arg android_value "$STABLE_VERSION,$RELEASE_DATE" \
          '.[$android_key] = $android_value')
          
        echo "$UPDATED_VERSION_JSON" > version.txt

        # 添加所有更改
        git add apk/ version.txt
        
        # 检查是否有更改
        if git diff-index --quiet HEAD --; then
          echo "没有需要提交的更改"
          exit 0
        fi

        # 提交更改
        git commit -m "更新稳定版本: $STABLE_VERSION (日期: $RELEASE_DATE)"
        
        # 推送到远程仓库
        echo "推送到远程仓库..."
        git remote set-url origin https://x-access-token:$TOKEN@github.com/${{ github.repository }}.git
        git push origin HEAD:${{ github.ref }}
        
        if [ $? -eq 0 ]; then
          echo "推送成功"
        else
          echo "错误: 推送失败，尝试强制推送..."
          git push --force origin HEAD:${{ github.ref }}
        fi

        echo "同步完成! 状态: 成功"
        echo "Android文件: $ANDROID_TARGET_PATH ($STABLE_VERSION, $RELEASE_DATE)"
        exit 0

    # =========== 新增锁释放步骤 ===========
    - name: Release Repository Lock
      if: always()
      run: |
        LOCK_FILE="$GITHUB_WORKSPACE/.lock/repo-lock"
        if [ -f "$LOCK_FILE" ]; then
          rm -f "$LOCK_FILE"
          echo "锁已释放"
        else
          echo "锁文件不存在，无需释放"
        fi

  cleanup_self:
    name: Cleanup Self Workflow History
    runs-on: ubuntu-latest
    needs: sync
    if: ${{ always() }}
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          keep_minimum_runs: 0
          retain_days: 0
          delete_workflow_pattern: "ServerBox Sync from Source Repository"
          repository: ${{ github.repository }}